'use strict';
const fs   = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const data    = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/trading_data.json'), 'utf8'));
const meses   = data.meses || {};
const dateData = {};
Object.keys(data).filter(k => k !== 'meses').sort().forEach(k => { dateData[k] = data[k]; });
const sorted = Object.keys(dateData);
const latest = sorted[sorted.length - 1];
const last7  = sorted.slice(-7);

// Flatten all posicoes_fechadas into a single array
const tradesData = [];
sorted.forEach(k => {
  const pf = dateData[k].posicoes_fechadas;
  if (Array.isArray(pf)) pf.forEach(t => tradesData.push(t));
});

const lines = [
  '// AUTO-GENERATED by scripts/extract.js — DO NOT EDIT MANUALLY',
  '// Updated: ' + new Date().toISOString(),
  'const TRADING_DATA = ' + JSON.stringify(dateData, null, 2) + ';',
  'const DATA_DATES   = ' + JSON.stringify(last7) + ';',
  'const LATEST_DATE  = ' + JSON.stringify(latest) + ';',
  'const MESES_DATA   = ' + JSON.stringify(meses, null, 2) + ';',
  'const TRADES_DATA  = ' + JSON.stringify(tradesData, null, 2) + ';',
  ''
];
fs.writeFileSync(path.join(ROOT, 'data.js'), lines.join('\n'));
console.log('data.js OK | latest: ' + latest + ' | dias: ' + sorted.length + ' | meses: ' + Object.keys(meses).join(', '));
