'use strict';
const fs   = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const data  = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/trading_data.json'), 'utf8'));
const meses = data.meses || {};

// ── RATING AUTOMÁTICO CTM ──
// Fórmula oficial: 0★ para qualquer perda, 1-5★ por lucro_pct.
// Escrito de volta para trading_data.json + injectado em TRADES_DATA.
function calcRating(t) {
  const pct = (t.lucro_pct != null) ? t.lucro_pct : null;
  if (pct === null) return 0;        // sem dados → 0★

  if (pct >= 30)  return 5;          // excepcional  ≥ 30%
  if (pct >= 20)  return 4;          // muito bom   20-29.9%
  if (pct >= 10)  return 3;          // bom         10-19.9%
  if (pct >= 5)   return 2;          // aceitável    5-9.99%
  if (pct >= 0)   return 1;          // marginal     0-4.99%
  return 0;                          // perda        < 0%
}

// Escreve ratings calculados de volta para trading_data.json
let jsonModified = false;
Object.keys(data).filter(k => /^\d{4}-\d{2}-\d{2}$/.test(k)).forEach(k => {
  const pf = data[k].posicoes_fechadas;
  if (Array.isArray(pf)) {
    pf.forEach(t => {
      if (t.ticker) {
        const r = calcRating(t);
        if (t.rating !== r) { t.rating = r; jsonModified = true; }
      }
    });
  }
});
if (jsonModified) {
  fs.writeFileSync(path.join(ROOT, 'data/trading_data.json'), JSON.stringify(data, null, 2));
  console.log('trading_data.json → ratings recalculados');
}

// Build dateData (já com ratings actualizados)
const dateData = {};
Object.keys(data).filter(k => /^\d{4}-\d{2}-\d{2}$/.test(k)).sort().forEach(k => { dateData[k] = data[k]; });
const sorted = Object.keys(dateData);
const latest = sorted[sorted.length - 1];
const last7  = sorted.slice(-7);
if (data.nav) dateData.nav = data.nav;   // [Fable] NAV exportado p/ nav.html (nunca contado como data)

// Flatten posicoes_fechadas → TRADES_DATA (rating já está no objecto)
const tradesData = [];
sorted.forEach(k => {
  const pf = dateData[k].posicoes_fechadas;
  if (Array.isArray(pf)) pf.forEach(t => tradesData.push(t));
});

const lines = [
  '// AUTO-GENERATED by scripts/_regen.js — DO NOT EDIT MANUALLY',
  '// Updated: ' + new Date().toISOString(),
  'const TRADING_DATA = ' + JSON.stringify(dateData, null, 2) + ';',
  'const DATA_DATES   = ' + JSON.stringify(last7) + ';',
  'const LATEST_DATE  = ' + JSON.stringify(latest) + ';',
  'const MESES_DATA   = ' + JSON.stringify(meses, null, 2) + ';',
  'const FUND_METRICS_DATA = ' + JSON.stringify(data.fund_metrics || {}) + ';',
  'const TRADES_DATA  = ' + JSON.stringify(tradesData, null, 2) + ';',
  ''
];
fs.writeFileSync(path.join(ROOT, 'data.js'), lines.join('\n'));
console.log('data.js OK | latest: ' + latest + ' | dias: ' + sorted.length + ' | meses: ' + Object.keys(meses).join(', '));
