#!/usr/bin/env node
/**
 * restore.js — lista ou restaura backups de trading_data.json
 *
 * Uso:
 *   node scripts/restore.js --list
 *   node scripts/restore.js --date 2025-04-16_1430
 */

'use strict';

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');

const ROOT       = path.join(__dirname, '..');
const BACKUP_DIR = path.join(ROOT, 'data', 'backups');
const DATA_FILE  = path.join(ROOT, 'data', 'trading_data.json');
const DATA_JS    = path.join(ROOT, 'data.js');

const args    = process.argv.slice(2);
const isList  = args.includes('--list');
const dateArg = args[args.indexOf('--date') + 1];

function getBackups() {
  if (!fs.existsSync(BACKUP_DIR)) return [];
  return fs.readdirSync(BACKUP_DIR)
    .filter(f => f.startsWith('trading_data_') && f.endsWith('.json'))
    .sort()
    .reverse(); // mais recente primeiro
}

function parseStamp(filename) {
  // trading_data_2025-04-16_1430.json → "2025-04-16 14:30"
  const m = filename.match(/trading_data_(\d{4}-\d{2}-\d{2})_(\d{2})(\d{2})\.json/);
  if (!m) return filename;
  return `${m[1]} ${m[2]}:${m[3]}`;
}

function listBackups() {
  const files = getBackups();
  if (!files.length) {
    console.log('Nenhum backup disponível em data/backups/');
    return;
  }
  console.log(`\nBackups disponíveis (${files.length}):\n`);
  files.forEach((f, i) => {
    let days = '?';
    try {
      const d = JSON.parse(fs.readFileSync(path.join(BACKUP_DIR, f), 'utf8'));
      days = Object.keys(d).length + ' dias';
    } catch (_) {}
    const stamp = parseStamp(f);
    const dateKey = f.replace('trading_data_','').replace('.json','');
    console.log(`  ${String(i+1).padStart(2)}. ${stamp}  [${days}]  → --date ${dateKey}`);
  });
  console.log('');
}

function regenerateDataJs(data) {
  const sorted = Object.keys(data).sort();
  const latest = sorted[sorted.length - 1];
  const last7  = sorted.slice(-7);
  const js = `// AUTO-GENERATED by scripts/restore.js — DO NOT EDIT MANUALLY
// Updated: ${new Date().toISOString()}
const TRADING_DATA = ${JSON.stringify(data, null, 2)};
const DATA_DATES   = ${JSON.stringify(last7)};
const LATEST_DATE  = "${latest}";
`;
  fs.writeFileSync(DATA_JS, js);
  console.log(`data.js regenerado (${sorted.length} dias, último: ${latest})`);
}

async function restoreDate(dateStr) {
  const files = getBackups();
  const match = files.find(f => f.includes(dateStr));
  if (!match) {
    console.error(`Backup não encontrado para: ${dateStr}`);
    console.error('Usa --list para ver backups disponíveis.');
    process.exit(1);
  }

  const backupPath = path.join(BACKUP_DIR, match);
  let backupData;
  try {
    backupData = JSON.parse(fs.readFileSync(backupPath, 'utf8'));
  } catch (e) {
    console.error(`Backup corrompido: ${e.message}`);
    process.exit(1);
  }

  const days = Object.keys(backupData).length;
  const stamp = parseStamp(match);
  console.log(`\nBackup a restaurar: ${stamp} — ${days} dias`);
  console.log(`Ficheiro: ${match}\n`);

  // confirmação
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  await new Promise(resolve => {
    rl.question(`Confirmar restauro? Isto vai SUBSTITUIR trading_data.json actual. (s/N) `, ans => {
      rl.close();
      if (ans.trim().toLowerCase() !== 's') {
        console.log('Restauro cancelado.');
        process.exit(0);
      }
      resolve();
    });
  });

  // backup do actual antes de restaurar
  if (fs.existsSync(DATA_FILE)) {
    const now = new Date();
    const pad = n => String(n).padStart(2,'0');
    const stamp2 = `${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}`;
    const safeguard = path.join(BACKUP_DIR, `trading_data_${stamp2}_pre-restore.json`);
    if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
    fs.copyFileSync(DATA_FILE, safeguard);
    console.log(`Actual guardado como safeguard: ${path.basename(safeguard)}`);
  }

  fs.writeFileSync(DATA_FILE, JSON.stringify(backupData, null, 2));
  console.log(`✅ trading_data.json restaurado (${days} dias)`);

  regenerateDataJs(backupData);
  console.log('\nRestauração completa. Valida e faz deploy com: npm run deploy\n');
}

// ── main ──
if (isList) {
  listBackups();
} else if (dateArg) {
  restoreDate(dateArg).catch(e => { console.error(e.message); process.exit(1); });
} else {
  console.log('Uso:');
  console.log('  node scripts/restore.js --list');
  console.log('  node scripts/restore.js --date 2025-04-16_1430');
  process.exit(1);
}
